export const GET_PRODUCTS_STARTED = "products/GET_PRODUCTS_STARTED";
export const GET_PRODUCTS_SUCCESS = "products/GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "products/GET_PRODUCTS_FAILED";

export const CREATE_PRODUCT_STARTED = "products/CREATE_PRODUCT_STARTED";
export const CREATE_PRODUCT_SUCCESS = "products/CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILED = "products/CREATE_PRODUCT_FAILED";