export const CATEGORY_STARTED = "category/CATEGORY_STARTED";
export const CATEGORY_SUCCESS = "category/CATEGORY_SUCCESS";
export const CATEGORY_FAILED = "category/CATEGORY_FAILED";

export const CATEGORY_SIDEMENU_GET_STARTED = "category/SIDEMENU_GET_STARTED";
export const CATEGORY_SIDEMENU_GET_SUCCESS = "category/SIDEMENU_GET_SUCCESS";
export const CATEGORY_SIDEMENU_GET_FAILED = "category/SIDEMENU_GET_FAILED";